{{- if .Values.rabbitmq.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  labels:
    {{- include "shopsys.labels" $ | nindent 4 }}
spec:
  serviceName: rabbitmq
  replicas: {{ .Values.rabbitmq.replicas }}
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      {{- with .Values.rabbitmq.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: rabbitmq
        {{- with .Values.rabbitmq.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- include "shopsys.podSettings" (dict "root" $ "component" .Values.rabbitmq) | nindent 6 }}
      containers:
        - name: rabbitmq
          image: {{ include "shopsys.image" .Values.rabbitmq.image | quote }}
          {{- with .Values.rabbitmq.image.pullPolicy }}
          imagePullPolicy: {{ . }}
          {{- end }}
          ports:
            - name: rabbitmq
              containerPort: 15672
              protocol: TCP
            - name: exporter
              containerPort: 15692
              protocol: TCP
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: {{ .Values.rabbitmq.auth.user | quote }}
            - name: RABBITMQ_DEFAULT_PASS
              value: {{ .Values.rabbitmq.auth.password | quote }}
            {{- with .Values.rabbitmq.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.rabbitmq.resources | nindent 12 }}
          {{- include "shopsys.containerSettings" .Values.rabbitmq | nindent 10 }}
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq
            {{- with .Values.rabbitmq.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      {{- with .Values.rabbitmq.extraVolumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: rabbitmq-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: {{ .Values.rabbitmq.persistence.storageClass }}
        resources:
          requests:
            storage: {{ .Values.rabbitmq.persistence.size }}
{{- end }}
