apiVersion: v1
kind: ConfigMap
metadata:
  name: production-php-opcache
  labels:
    {{- include "shopsys.labels" $ | nindent 4 }}
data:
  php-opcache.ini: |
    {{- .Values.webserver.phpFpm.opcacheConfig | nindent 4 }}
