apiVersion: v1
kind: ConfigMap
metadata:
  name: domains-urls
  labels:
    {{- include "shopsys.labels" $ | nindent 4 }}
data:
  {{ .Values.app.domainsUrls.filename }}: |
    {{- include "shopsys.domainsUrls.data" . | nindent 4 }}
