apiVersion: v1
kind: ConfigMap
metadata:
  name: production-php-fpm
  labels:
    {{- include "shopsys.labels" $ | nindent 4 }}
data:
  www.conf: |
    {{- .Values.webserver.phpFpm.config | nindent 4 }}
