{{- if and .Values.registry.create .Values.registry.server (not .Values.registry.existingSecret) }}
{{- $auth := printf "%s:%s" .Values.registry.username .Values.registry.password | b64enc }}
{{- $config := dict "auths" (dict .Values.registry.server (dict "username" .Values.registry.username "password" .Values.registry.password "email" .Values.registry.email "auth" $auth)) }}
apiVersion: v1
kind: Secret
metadata:
  name: dockerregistry
  labels:
    {{- include "shopsys.labels" $ | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ $config | toJson | b64enc }}
{{- end }}
