{{- if and (include "shopsys.httpAuthNeeded" .) .Values.security.httpAuth.htpasswd }}
apiVersion: v1
kind: Secret
metadata:
  name: http-auth
  labels:
    {{- include "shopsys.labels" $ | nindent 4 }}
type: Opaque
stringData:
  auth: {{ .Values.security.httpAuth.htpasswd | quote }}
{{- end }}
