apiVersion: v1
kind: Service
metadata:
  name: storefront
  labels:
    {{- include "shopsys.labels" $ | nindent 4 }}
spec:
  selector:
    app: storefront
  ports:
    - name: storefront
      port: 3000
      targetPort: 3000
